export const ProjectsData = [
  {
    titleId: "projects.foods.title",
    descriptionId: "projects.foods.description",
    images: ["projects/food/screen1.png"],
    isWorkExperience: false,
    categoryId: "category.own",
    startDate: "1/12/2021",
    finalDate: "9/12/2021",
    technologies: [
      "React",
      "Redux",
      "JS",
      "NodeJS",
      "Sequelize",
      "PostgreSQL",
      "React Query",
      "Redux",
      "CSS",
    ],
    typeOfProject: "FULL STACK",
    isResponsiveId: "is.food.responsive",
    link: "",
    repositoryLink: "https://github.com/Florencia-coder/P-I",
  },
  {
    titleId: "projects.vitau.title",
    descriptionId: "projects.vitau.description",
    images: ["projects/vitau_logo.jpg"],
    isWorkExperience: true,
    categoryId: "category.work",
    startDate: "14 Feb 2022",
    finalDate: "9 Ago 2023",
    technologies: [
      "React",
      "NodeJS",
      "Sequelize",
      "PostgreSQL",
      "React Query",
      "Redux",
      "CSS",
    ],
    typeOfProject: "FRONTEND MOBILE",
    isResponsiveId: "is.vitau.responsive",
    link: "",
    repositoryLink: "",
  },
  {
    titleId: "projects.webNotes.title",
    descriptionId: "projects.webNotes.description",
    images: [
      "projects/web-notes/screen1.png",
      "projects/web-notes/screen2.png",
    ],
    isWorkExperience: false,
    categoryId: "category.own",
    startDate: "1 Sep 2023",
    finalDate: "3 Nov 2023",
    repositoryLink: "https://github.com/Florencia-coder/web-notes.git",
    technologies: [
      "NodeJS",
      "Expresss",
      "Sequelize",
      "PostgreSQL",
      "ReactJS",
      "JS",
      "CSS3",
    ],
    link: "",
    repositoryLink: "https://github.com/Florencia-coder/web-notes",
    typeOfProject: "FULL STACK",
    isResponsiveId: "is.webNotes.responsive",
  },
  {
    titleId: "projects.kies.title",
    descriptionId: "projects.kies.description",
    images: [
      "projects/kies/prev.png",
      "projects/kies/screen1.png",
      "projects/kies/screen2.png",
      "projects/kies/screen3.png",
      "projects/kies/screen4.png",
      "projects/kies/screen5.png",
      "projects/kies/screen6.png",
      "projects/kies/screen7.png",
      "projects/kies/screen8.png",
    ],
    isWorkExperience: false,
    categoryId: "category.freelance",
    startDate: "26 Sep 2024",
    finalDate: "1 Dic 2024",
    technologies: ["Python", "Flask", "CSS3", "HTML", "Render"],
    typeOfProject: "FULL STACK",
    isResponsiveId: "is.kies.responsive",
    link: "https://kies.onrender.com/",
    repositoryLink: "https://github.com/Florencia-coder/KiEs",
  },
  {
    titleId: "projects.materialFs.title",
    descriptionId: "projects.materialFs.description",
    images: [
      "projects/material-fs/screen1.png",
      "projects/material-fs/screen2.png",
      "projects/material-fs/screen3.png",
      "projects/material-fs/screen4.png",
      "projects/material-fs/screen5.png",
      "projects/material-fs/screen6.png",
      "projects/material-fs/screen7.png",
      "projects/material-fs/screen8.png",
      "projects/material-fs/screen9.png",
      "projects/material-fs/screen10.png",
      "projects/material-fs/screen11.png",
      "projects/material-fs/screen12.png",
    ],
    categoryId: "category.entrepreneurship",
    startDate: "1 Ene 2025",
    finalDate: "Actualidad",
    repositoryLink: "https://github.com/Florencia-coder/KiEs.git",
    isWorkExperience: false,
    technologies: ["Git", "GitHub", "JS", "React", "Redux"],
    typeOfProject: "FRONTEND",
    isResponsiveId: "is.materialFs.responsive",
    link: "",
    repositoryLink: "",
  },
  {
    titleId: "projects.ticketazo.title",
    descriptionId: "projects.ticketazo.description",
    images: [
      "projects/ticketazo/screen1.png",
      "projects/ticketazo/screen2.png",
    ],
    categoryId: "category.own",
    startDate: "14 Feb 2025",
    finalDate: "1 Mar 2025",
    repositoryLink: "https://github.com/Florencia-coder/tiquetazo-system.git",
    isWorkExperience: false,
    technologies: ["React", "CSS3", "Json-server"],
    typeOfProject: "FULL STACK",
    isResponsiveId: "is.ticketazo.responsive",
    link: "",
    repositoryLink: "https://github.com/Florencia-coder/tiquetazo-system",
  },
  {
    titleId: "projects.portfolio.title",
    descriptionId: "projects.portfolio.description",
    images: ["projects/portfolio/screen1.png"],
    categoryId: "category.own",
    startDate: "1 Mar 2025",
    finalDate: "27 Mar 2025",
    repositoryLink: "https://github.com/Florencia-coder/mi-camino-dev",
    isWorkExperience: false,
    technologies: ["React", "CSS3"],
    typeOfProject: "FRONTEND",
    isResponsiveId: "is.portfolio.responsive",
  },
  {
    titleId: "projects.paint.title",
    descriptionId: "projects.paint.description",
    images: ["projects/paint/screen1.png", "projects/paint/screen2.png"],
    categoryId: "category.own",
    startDate: "28 Mar 2025",
    finalDate: "30 Mar 2025",
    link: "https://paint-nine-sandy.vercel.app/",
    repositoryLink: "https://github.com/Florencia-coder/paint.git",
    isWorkExperience: false,
    technologies: ["React", "CSS3"],
    typeOfProject: "FRONTEND",
    isResponsiveId: "is.paint.responsive",
  },
];
