export const ProjectsData = [
  {
    title: "Food's",
    images: ["projects/food/screen1.png"],
    isWorkExperience: false,
    category: "Proyecto propio",
    startDate: "1/12/2021",
    finalDate: "9/12/2021",
    technologies: [
      "React",
      "Redux",
      "JS",
      "NodeJS",
      "Sequelize",
      "PostgreSQL",
      "React Query",
      "Redux",
      "CSS",
    ],
    typeOfProject: "FULL STACK",
    isResponsive: true,
    link: "",
    repositoryLink: "https://github.com/Florencia-coder/P-I",
    description: `Mi primer proyecto: una Single Page Application (SPA) que muestra recetas de comida obtenidas desde una API externa. Además, permite a los usuarios agregar sus propias recetas, almacenándolas en una base de datos. Cuenta con filtros avanzados por nombre, tipo de dieta, puntaje y más.`,
  },
  {
    title: "Vitau.mx",
    images: ["projects/vitau_logo.jpg"],
    isWorkExperience: true,
    category: "Experiencia laboral",
    startDate: "14 Feb 2022",
    finalDate: "9 Ago 2023",
    technologies: [
      "React",
      "NodeJS",
      "Sequelize",
      "PostgreSQL",
      "React Query",
      "Redux",
      "CSS",
    ],
    typeOfProject: "FRONTEND MOBILE",
    isResponsive: true,
    link: "",
    repositoryLink: "",
    description: `Mi primer proyecto: una Single Page Application (SPA) que muestra recetas de comida obtenidas desde una API externa. Además, permite a los usuarios agregar sus propias recetas, almacenándolas en una base de datos. Cuenta con filtros avanzados por nombre, tipo de dieta, puntaje y más.`,
  },
  {
    title: "Web Notes",
    images: [
      "projects/web-notes/screen1.png",
      "projects/web-notes/screen2.png",
    ],
    isWorkExperience: false,
    category: "Proyecto propio",
    startDate: "1 Sep 2023",
    finalDate: "3 Nov 2023",
    repositoryLink: "https://github.com/Florencia-coder/web-notes.git",
    technologies: [
      "NodeJS",
      "Expresss",
      "Sequelize",
      "PostgreSQL",
      "ReactJS",
      "JS",
      "CSS3",
    ],
    link: "",
    repositoryLink: "https://github.com/Florencia-coder/web-notes",
    typeOfProject: "FULL STACK",
    description: `Desarrollé este proyecto tras notar que la gestión de notas era una funcionalidad recurrente en pruebas técnicas. Me pareció un desafío interesante, así que lo construí con un enfoque completo. Es una SPA que permite realizar un ABM (Alta, Baja, Modificación y Consulta) de notas, archivarlas, cambiar el tema y es completamente responsive.`,
  },
  {
    title: "KiEs",
    images: [
      "projects/kies/prev.png",
      "projects/kies/screen1.png",
      "projects/kies/screen2.png",
      "projects/kies/screen3.png",
      "projects/kies/screen4.png",
      "projects/kies/screen5.png",
      "projects/kies/screen6.png",
      "projects/kies/screen7.png",
      "projects/kies/screen8.png",
    ],
    isWorkExperience: false,
    category: "Freelance",
    startDate: "26 Sep 2024",
    finalDate: "1 Dic 2024",
    technologies: ["Python", "Flask", "CSS3", "HTML", "Render"],
    typeOfProject: "FULL STACK",
    link: "https://kies.onrender.com/",
    repositoryLink: "https://github.com/Florencia-coder/KiEs",
    description: `La plataforma KiEs fue desarrollada junto a un exelente amigo y compañero, Lucas. Es una plataforma web de kinesiología para un cliente. Permite registrar pacientes con su DNI y realizar tres análisis: ventral (imagen o cámara en vivo), lateral (imagen de perfil) y de apófisis espinosas. En cada análisis, se pueden marcar puntos clave en el cuerpo y obtener un resultado estimado. También genera un PDF con el análisis realizado.`,
  },
  {
    title: "Material FullStack",
    images: [
      "projects/material-fs/screen1.png",
      "projects/material-fs/screen2.png",
      "projects/material-fs/screen3.png",
      "projects/material-fs/screen4.png",
      "projects/material-fs/screen5.png",
      "projects/material-fs/screen6.png",
      "projects/material-fs/screen7.png",
      "projects/material-fs/screen8.png",
      "projects/material-fs/screen9.png",
      "projects/material-fs/screen10.png",
      "projects/material-fs/screen11.png",
      "projects/material-fs/screen12.png",
    ],
    category: "Emprendimiento",
    startDate: "1 Ene 2025",
    finalDate: "Actualidad",
    repositoryLink: "https://github.com/Florencia-coder/KiEs.git",
    isWorkExperience: false,
    technologies: ["Git", "GitHub", "JS", "React", "Redux"],
    typeOfProject: "FRONTEND",
    link: "",
    repositoryLink: "",
    description: `Mi objetivo con este proyecto es compartir mis conocimientos como desarrolladora FullStack de la manera más accesible posible. Creé material en Notion, recopilando información de documentaciones oficiales, material de estudio que usé al comenzar, herramientas de IA y mi experiencia en el campo. No solo cuenta con material y ejemplos, si no que tambien he agregado secciones de "Notas Importantes", "Buenas Prácticas" y más. Planeo seguir ampliándolo con ejercicios prácticos para reforzar el aprendizaje y hacerlo accesible a más personas.`,
  },
  {
    title: "Ticketazo System",
    images: [
      "projects/ticketazo/screen1.png",
      "projects/ticketazo/screen2.png",
    ],
    category: "Proyecto propio",
    startDate: "14 Feb 2025",
    finalDate: "1 Mar 2025",
    repositoryLink: "https://github.com/Florencia-coder/tiquetazo-system.git",
    isWorkExperience: false,
    technologies: ["React", "CSS3", "Json-server"],
    typeOfProject: "FULL STACK",
    link: "",
    repositoryLink: "https://github.com/Florencia-coder/tiquetazo-system",
    description:
      "Este proyecto nació para solucionar un problema común en los bares: el desorden en la toma de pedidos. Ticketazo System permite a los clientes realizar pedidos directamente desde la mesa, compartirlos con otras personas y gestionar múltiples órdenes en una misma mesa. Es una solución simple pero efectiva, con una interfaz responsive para facilitar su uso desde cualquier dispositivo.",
  },
  {
    title: "Mi Portfolio",
    images: ["projects/portfolio/screen1.png"],
    category: "Proyecto propio",
    startDate: "1 Mar 2025",
    finalDate: "27 Mar 2025",
    repositoryLink: "",
    isWorkExperience: false,
    technologies: ["React", "CSS3"],
    typeOfProject: "FRONTEND",
    description:
      "Este proyecto era una idea que tenía en mente desde hace tiempo, pero no lograba encontrar el estilo que realmente me representara. Probé varias versiones anteriormente, pero ninguna terminaba de convencerme. Siento que esta versión es la que más se acerca a lo que me gusta, y durante el proceso de diseño descubrí cuánto más puedo explorar con CSS y sus increíbles efectos.",
  },
];
